package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hamza-m-masood/camunda-chart-doctor/internal/upgrade"
	"gopkg.in/yaml.v3"
)

// runGenerate regenerates the embedded migration data from a camunda-platform-helm
// checkout. This is a maintainer command, not part of the user-facing surface: the
// binary ships the generated data, so an operator never needs a chart checkout.
func runGenerate(args []string) int {
	fs := flag.NewFlagSet("generate", flag.ContinueOnError)
	chartRepo := fs.String("chart-repo", "", "path to a camunda-platform-helm checkout")
	outDir := fs.String("out", "internal/upgrade/data", "directory to write manifests into")
	linesFlag := fs.String("lines", "8.6,8.7,8.8,8.9,8.10", "comma-separated Camunda lines")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *chartRepo == "" {
		fmt.Fprintln(os.Stderr, "error: --chart-repo is required")
		return 2
	}
	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 2
	}
	for _, raw := range strings.Split(*linesFlag, ",") {
		line, err := upgrade.ParseLine(strings.TrimSpace(raw))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			return 2
		}
		m, err := upgrade.Extract(*chartRepo, line)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			return 2
		}
		body, err := yaml.Marshal(m)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			return 2
		}
		header := fmt.Sprintf(
			"# Generated by `camunda-chart-doctor generate`. Do not edit by hand.\n"+
				"# Source: charts/camunda-platform-%s/templates/*/constraints.tpl\n", line)
		path := filepath.Join(*outDir, line.String()+".yaml")
		if err := os.WriteFile(path, append([]byte(header), body...), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			return 2
		}
		removed, renamed, deprecated := m.Counts()
		fmt.Printf("%-5s chart %d.x  %3d keys (%d removed, %d renamed, %d deprecated)  -> %s\n",
			line, m.ChartMajor, len(m.Keys), removed, renamed, deprecated, path)
	}
	return 0
}
