package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/hamza-m-masood/camunda-helm-toolkit/internal/helmrender"
	"github.com/hamza-m-masood/camunda-helm-toolkit/internal/monitorgen"
	"github.com/hamza-m-masood/camunda-helm-toolkit/internal/values"
)

func runScaffoldMonitoring(args []string) int {
	fs := flag.NewFlagSet("scaffold-monitoring", flag.ContinueOnError)
	release := fs.String("release", "", "release name used for the generated resources' own names (required)")
	namespace := fs.String("namespace", "default", "kubernetes namespace")
	fs.StringVar(namespace, "n", "default", "kubernetes namespace (shorthand)")
	chart := fs.String("chart", "", "path to the chart to render (required)")
	var valueFiles multiFlag
	fs.Var(&valueFiles, "f", "values overlay file (repeatable)")
	outputFile := fs.String("output-file", "", "write to this path instead of stdout")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *release == "" || *chart == "" {
		fmt.Fprintln(os.Stderr, "error: --release and --chart are both required")
		return 2
	}

	base, err := helmrender.ShowValues(*chart)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 2
	}
	merged, err := values.ParseYAML(base)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 2
	}
	for _, f := range valueFiles {
		ov, err := loadYAMLFile(f)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error loading", f, ":", err)
			return 2
		}
		merged = values.DeepMerge(merged, ov)
	}

	docs, err := renderManifests(*chart, merged)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error rendering chart:", err)
		return 2
	}

	services := monitorgen.DiscoverServices(docs)
	var out strings.Builder
	fmt.Fprintln(&out, "# Generated by camunda-helm-toolkit scaffold-monitoring — review before applying.")
	fmt.Fprintln(&out, "# ServiceMonitor port names are taken from the chart's OWN rendered Service")
	fmt.Fprintln(&out, "# objects, not hardcoded, so they cannot drift out of sync with what the chart")
	fmt.Fprintln(&out, "# actually exposes.")
	fmt.Fprintln(&out)
	fmt.Fprint(&out, monitorgen.GenerateServiceMonitors(*release, *namespace, services))
	fmt.Fprint(&out, monitorgen.GeneratePrometheusRule(*release, *namespace))

	if *outputFile != "" {
		if err := os.WriteFile(*outputFile, []byte(out.String()), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "error writing", *outputFile, ":", err)
			return 2
		}
		fmt.Fprintln(os.Stderr, "wrote", *outputFile, "— review it, then kubectl apply -f it yourself; nothing is auto-applied.")
		return 0
	}
	fmt.Print(out.String())
	return 0
}
