package main

import (
	"flag"
	"fmt"
	"os"
)

const watcherImageDefault = "ghcr.io/hamza-m-masood/camunda-helm-toolkit:latest"

func runScaffoldWatcher(args []string) int {
	fs := flag.NewFlagSet("scaffold-watcher", flag.ContinueOnError)
	release := fs.String("release", "", "installed release name (required)")
	namespace := fs.String("namespace", "default", "kubernetes namespace")
	fs.StringVar(namespace, "n", "default", "kubernetes namespace (shorthand)")
	schedule := fs.String("schedule", "*/30 * * * *", "cron schedule for the watch job")
	webhookURL := fs.String("webhook-url", "", "POST new findings here as JSON; if unset, the job just logs them")
	image := fs.String("image", watcherImageDefault, "container image to run (pin to a specific tag for production use)")
	outputFile := fs.String("output-file", "", "write to this path instead of stdout")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *release == "" {
		fmt.Fprintln(os.Stderr, "error: --release is required")
		return 2
	}

	saName := *release + "-helm-toolkit-watcher"
	stateName := *release + "-helm-toolkit-state"
	webhookArgs := ""
	if *webhookURL != "" {
		webhookArgs = fmt.Sprintf("            - --webhook-url\n            - %q\n", *webhookURL)
	}

	manifest := fmt.Sprintf(`# Generated by camunda-helm-toolkit scaffold-watcher — review before applying.
# Nothing is auto-applied; this is output only.
#
# RBAC is scoped to exactly what watch-once needs, in this one namespace only:
# read PDBs/secrets/pods to compute findings, and read/write one ConfigMap to
# remember what was already reported.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: %s
  namespace: %s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: %s
  namespace: %s
rules:
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets", "pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["%s"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"] # first run: the named ConfigMap doesn't exist yet to scope resourceNames to
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: %s
  namespace: %s
subjects:
  - kind: ServiceAccount
    name: %s
    namespace: %s
roleRef:
  kind: Role
  name: %s
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: %s-helm-toolkit-watch
  namespace: %s
spec:
  schedule: %q
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: %s
          restartPolicy: Never
          containers:
            - name: helm-toolkit-watch
              image: %s
              args:
                - watch-once
                - --release
                - %q
                - --namespace
                - %q
%s`,
		saName, *namespace,
		saName, *namespace, stateName,
		saName, *namespace, saName, *namespace, saName,
		*release, *namespace, *schedule, saName, *image, *release, *namespace, webhookArgs)

	if *outputFile != "" {
		if err := os.WriteFile(*outputFile, []byte(manifest), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "error writing", *outputFile, ":", err)
			return 2
		}
		fmt.Fprintln(os.Stderr, "wrote", *outputFile, "— review it, then kubectl apply -f it yourself; nothing is auto-applied.")
		return 0
	}
	fmt.Print(manifest)
	return 0
}
